name: CI/CD Staging Deployment

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-staging:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Start Staging Environment
      run: |
        pm2 start npm --name "staging-app" -- start
        echo "Staging app started. Access it at http://<staging-server-ip>:3000"

  stop-staging:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
    - name: Stop Staging Environment
      run: |
        pm2 stop staging-app
        pm2 delete staging-app
        echo "Staging app stopped."

